openapi: 3.1.0
info:
  title: Template manuell regel API
  version: 1.0.0
  description: Template för manuell regel OpenAPI.

paths:
  /{handlaggningId}:
    get:
      tags: [RegelTemplateController]
      operationId: getData
      summary: Hämta information som behövs för uppgiften
      description: Hämta information som behövs för uppgiften
      parameters:
        - $ref: "#/components/parameters/HandlaggningId"
      responses:
        "200":
          description: Information hämtad OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetDataResponse"
        "400":
          description: Ogiltig begäran
        "404":
          description: Informationen hittades inte
    patch:
      tags: [RegelTemplateController]
      operationId: updateData
      summary: Uppdatera information
      description: Uppdatera information
      parameters:
        - $ref: "#/components/parameters/HandlaggningId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PatchDataRequest"
      responses:
        "204":
          description: Uppdatering genomförd OK
        "400":
          description: Ogiltig begäran
        "404":
          description: Informationen hittades inte

components:
  parameters:
    HandlaggningId:
      name: handlaggningId
      in: path
      required: true
      description: ID för handläggningsärendet
      schema:
        type: string
        format: uuid

  schemas:
    GetDataResponse:
      type: object
      properties:
        handlaggning_id:
          type: string
          format: uuid
        template_get_data:
          $ref: "#/components/schemas/TemplateGetData"

    PatchDataRequest:
      type: object
      properties:
        template_patch_data:
          $ref: "#/components/schemas/TemplatePatchData"

    TemplateGetData:
      type: object
      properties:
        template_my_get_data_attribute:
          type: string

    TemplatePatchData:
      type: object
      properties:
        template_my_patch_data_attribute:
          type: string
